version: "2"
exclude_patterns:
  - ".*/"
  - "docs/"
  - "**/node_modules/"
  - "SampleApp/"
  - "scripts/"
  - "**/__mocks__/"
  - "**/__tests__/"
  - "**/.*"
  - "**/*.config.js"
  - "**/*.h"
  - "**/*.json"
  - "**/*.md"
  - "**/*.plist"
  - "**/*.podspec"
  - "**/*.xcodeproj"
  - "**/*.xcworkspace"
  - "**/*.yml"
  - "**/build.gradle"
  - "**/AndroidManifest.xml"
