name: actions

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install zee dependencies
        run: cd integration-testing/  && yarn install

      - name: pod install
        run: cd integration-testing/ios/ && pod install

      - name: Build and test
        run: |
          xcodebuild test -workspace example.xcworkspace -scheme example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' CODE_SIGNING_REQUIRED=NO | xcpretty || exit 1
